### ISSUE TITLE
TypeError: must be encoded string without NULL bytes, not unicode

### ISSUE THREAD

**Issue by shamoons** [ellisdg/3DUnetCNN#177]
When I run `>>> convert_brats_data("data/original", "data/preprocessed")`, I get this error:

```
[Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "preprocess.py", line 168, in convert_brats_data
    no_bias_correction_modalities=no_bias_correction_modalities)
  File "preprocess.py", line 133, in convert_brats_folder
    normalize_image(image_file, out_file, bias_correction=perform_bias_correction)
  File "preprocess.py", line 114, in normalize_image
    correct_bias(in_file, out_file)
  File "preprocess.py", line 71, in correct_bias
    done = correct.run()
  File "/home/parallels/.pyenv/versions/2.7/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 349, in run
    version=self.version)
  File "/home/parallels/.pyenv/versions/2.7/lib/python2.7/site-packages/nipype/interfaces/ants/base.py", line 125, in version
    return Info.version()
  File "/home/parallels/.pyenv/versions/2.7/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 1054, in version
    terminal_output='allatonce').run()
  File "/home/parallels/.pyenv/versions/2.7/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 369, in run
    runtime = self._run_interface(runtime)
  File "/home/parallels/.pyenv/versions/2.7/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 737, in _run_interface
    cmd_path = which(executable_name, env=runtime.environ)
  File "/home/parallels/.pyenv/versions/2.7/lib/python2.7/site-packages/nipype/utils/filemanip.py", line 872, in which
    if isexec(filename):
  File "/home/parallels/.pyenv/versions/2.7/lib/python2.7/site-packages/nipype/utils/filemanip.py", line 861, in isexec
    return os.path.isfile(path) and os.access(path, os.X_OK)
  File "/home/parallels/.pyenv/versions/2.7/lib/python2.7/genericpath.py", line 29, in isfile
    st = os.stat(path)
TypeError: must be encoded string without NULL bytes, not unicode
>>> 
```
I'm running on Ubuntu 16.04 with Python 2.7 (via pyenv)

**Comment by ellisdg** [comment]
Try using Python 3.

**Comment by shamoons** [comment]
That fixed it. Thanks.
