### ISSUE TITLE
OSError: No command "N4BiasFieldCorrection" found on host ubuntu. Please check that the corresponding package is installed.

### ISSUE THREAD

**Issue by shamoons** [ellisdg/3DUnetCNN#178]
Getting this error:

```
OSError: No command "N4BiasFieldCorrection" found on host ubuntu. Please check that the corresponding package is installed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/parallels/.pyenv/versions/3.6.8/lib/python3.6/site-packages/SimpleITK/SimpleITK.py", line 3709, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, Image, name, value)
KeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/psf/Home/Sites/rowan/3DUnetCNN/brats/preprocess.py", line 168, in convert_brats_data
  File "/media/psf/Home/Sites/rowan/3DUnetCNN/brats/preprocess.py", line 133, in convert_brats_folder
    # copy the truth file
  File "/media/psf/Home/Sites/rowan/3DUnetCNN/brats/preprocess.py", line 114, in normalize_image
    else:
  File "/media/psf/Home/Sites/rowan/3DUnetCNN/brats/preprocess.py", line 79, in correct_bias
    sitk.WriteImage(output_image, out_file)
  File "/home/parallels/.pyenv/versions/3.6.8/lib/python3.6/site-packages/SimpleITK/SimpleITK.py", line 51761, in N4BiasFieldCorrection
    return _SimpleITK.N4BiasFieldCorrection(*args)
SystemError: <built-in function N4BiasFieldCorrection> returned a result with an error set
```

Ubuntu 16.04
Python 3.6.8

I installed ant and set the path

**Comment by ellisdg** [comment]
Does "N4BiasFieldCorrection" work if you run it in the terminal?

**Comment by chestnut111** [comment]
the same problem

**Comment by chestnut111** [comment]
i fixed it , because i make the path wrong.......

**Comment by hassaanmahmood** [comment]
I

> i fixed it , because i make the path wrong.......

I am also getting same error. I added the bin path to python system path and also in conda path. still geting same error... any input?
Do I need to compile and follow who
le procedure of getting ANTs library or copying Bin file ie ok?
