### ISSUE TITLE
BRATS2018 data seems to be in the right location, but not being read

### ISSUE THREAD

**Issue by shamoons** [ellisdg/3DUnetCNN#179]
I tried

`convert_brats_data("/media/psf/Home/Sites/rowan/Inception-Unet/Data", "data/preprocessed")`

The error I get is

```
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/psf/Home/Sites/rowan/3DUnetCNN/brats/preprocess.py", line 165, in convert_brats_data
    no_bias_correction_modalities=no_bias_correction_modalities)
  File "/media/psf/Home/Sites/rowan/3DUnetCNN/brats/preprocess.py", line 128, in convert_brats_folder
    raise error
  File "/media/psf/Home/Sites/rowan/3DUnetCNN/brats/preprocess.py", line 122, in convert_brats_folder
    image_file = get_image(in_folder, name)
  File "/media/psf/Home/Sites/rowan/3DUnetCNN/brats/preprocess.py", line 94, in get_image
    raise RuntimeError("Could not find file matching {}".format(file_card))
RuntimeError: Could not find file matching /media/psf/Home/Sites/rowan/Inception-Unet/Data/BRATS_2018/HGG/*t1.nii.gz

```

Any ideas what I could be doing wrong?

Ubuntu 16.04
Python 3.6.8

**Comment by ellisdg** [comment]
Try running:
```
convert_brats_data("/media/psf/Home/Sites/rowan/Inception-Unet/Data/BRATS_2018", "data/preprocessed")
```

If that doesn't work, make sure your folder structure is correct. In your BRATS_2018 folder, you should have two subject folders: 'HGG' and 'LGG'. Then each of those folders you should have the subject folders. Then in each of the subject folders should be the images.
