### ISSUE TITLE
Change in config file doesn't reflect in running code

### ISSUE THREAD

**Issue by divinediu** [ellisdg/3DUnetCNN#212]
Hi! I am trying to figure out how to get this to run.
```
convert_brats_data("data/original", "data/preprocessed")
Traceback (most recent call last):
  File "/mnt/d/JupyterNotebooks/4.3DUnetCNN/2.3DUnetCNN-Larynx/brats/preprocess.py", line 92, in get_image
    return glob.glob(file_card)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/d/JupyterNotebooks/4.3DUnetCNN/2.3DUnetCNN-Larynx/brats/preprocess.py", line 164, in convert_brats_data
    no_bias_correction_modalities=no_bias_correction_modalities)
  File "/mnt/d/JupyterNotebooks/4.3DUnetCNN/2.3DUnetCNN-Larynx/brats/preprocess.py", line 128, in convert_brats_folder
    raise error
  File "/mnt/d/JupyterNotebooks/4.3DUnetCNN/2.3DUnetCNN-Larynx/brats/preprocess.py", line 122, in convert_brats_folder
    image_file = get_image(in_folder, name)
  File "/mnt/d/JupyterNotebooks/4.3DUnetCNN/2.3DUnetCNN-Larynx/brats/preprocess.py", line 94, in get_image
    raise RuntimeError("Could not find file matching {}".format(file_card))
RuntimeError: Could not find file matching data/original/Larynx/22_t2/*t1.nii.gz
```
I have changed this particular line in my config file:

`config["all_modalities"] = ["nca", "seg"]`

My folder structure is data/original/Larynx/ID/
I have files:
_nca.nii
_seg.nii.gz

What's happening?

**Comment by Iamyourbaba** [comment]
Have you finished the problem?

**Comment by ellisdg** [comment]
@Iamyourbaba are you getting hung up on the preprocessing step or is it the training step? If you haven't already, trying running just the training step without the preprocessing.
