### ISSUE TITLE
image_shape only identical multiples of 16?

### ISSUE THREAD

**Issue by saskra** [ellisdg/3DUnetCNN#224]
https://github.com/ellisdg/3DUnetCNN/blob/dc2d0604499298266e7aaf1db68603288bd34577/brats/train_isensee2017.py#L11

Why are only multiples of 16 allowed for the image dimensions? It works with 128 and 144, for example, but not with all the numbers in between. And why do all three dimensions have to be of the same size? For example "240, 240, 144" does not work although it would preferred due to being close to the original resolution.

```shell
Traceback (most recent call last):
  File "/home/x/PycharmProjects/3DUnetCNN/brats/train_isensee2017.py", line 123, in <module>
    main(overwrite=config["overwrite"])
  File "/home/x/PycharmProjects/3DUnetCNN/brats/train_isensee2017.py", line 85, in main
    n_base_filters=config["n_base_filters"])
  File "/home/x/PycharmProjects/3DUnetCNN/unet3d/model/isensee2017.py", line 59, in isensee2017_model
    concatenation_layer = concatenate([level_output_layers[level_number], up_sampling], axis=1)
  File "/home/x/anaconda3/envs/3DUnetCNN/lib/python3.6/site-packages/keras/layers/merge.py", line 649, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/home/x/anaconda3/envs/3DUnetCNN/lib/python3.6/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/x/anaconda3/envs/3DUnetCNN/lib/python3.6/site-packages/keras/layers/merge.py", line 362, in build
    'Got inputs shapes: %s' % (input_shape))
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 128, 17, 17, 17), (None, 128, 18, 18, 18)]
Closing remaining open files:/home/x/PycharmProjects/3DUnetCNN/brats/brats_data.h5...done

Process finished with exit code 1
```

**Comment by parvezamu** [comment]
It's because of 4 stridden convolution layers of size 2.................that is 128/16=8...that is the first level is 128...then next 64....then next 32......then next 16...then next 8.....8 is the last level of encoder...after that.....the Upsampling layer of size 2....upsamples the original resolution of 8 to 16 and then features concatenation....then next upsample operation enhance the size to 32...and so on................suppose the input patch size is 124.....then due to stridden convolution layers the next level is 62...then 31...then 15.....then how could you upsample the size 15 to 31...for performing the skip-connection operation...................
