### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by v-ghobadi** [ellisdg/3DUnetCNN#276]
I have encountered  this TypeError:
TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type int8 of argument 'x'. in
weighted_dice_coefficient  *
        return K.mean(2. * (K.sum(y_true * y_pred, ...
Can anyone help please?

**Comment by ellisdg** [comment]
Hello,
Could you copy and paste the full error message, please?

**Comment by v-ghobadi** [comment]
Hello, 
Thank you for your reply and efforts to develop and update 3dUNetCNN code. this is the full error:

Number of training steps:  295
Number of validation steps:  37
WARNING:tensorflow:From /content/drive/MyDrive/3DUnetCNN/unet3d/training.py:88: Model.fit_generator (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
Please use Model.fit, which supports generators.
Epoch 1/500
Traceback (most recent call last):
  File "train.py", line 125, in <module>
    main(overwrite=config["overwrite"])
  File "train.py", line 120, in main
    n_epochs=config["n_epochs"])
  File "/content/drive/MyDrive/3DUnetCNN/unet3d/training.py", line 88, in train_model
    early_stopping_patience=early_stopping_patience))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1829, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:806 train_function  *
        return step_function(self, iterator)
    /content/drive/MyDrive/3DUnetCNN/unet3d/metrics.py:50 weighted_dice_coefficient_loss  *
        return -weighted_dice_coefficient(y_true, y_pred)
    /content/drive/MyDrive/3DUnetCNN/unet3d/metrics.py:44 weighted_dice_coefficient  *
        return K.mean(2. * (K.sum(y_true * y_pred,
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:1140 binary_op_wrapper
        raise e
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:1124 binary_op_wrapper
        return func(x, y, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:1456 _mul_dispatch
        return multiply(x, y, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:508 multiply
        return gen_math_ops.mul(x, y, name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py:6176 mul
        "Mul", x=x, y=y, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:506 _apply_op_helper
        inferred_from[input_arg.type_attr]))

    TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type int8 of argument 'x'.
