### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Nhunguts** [ellisdg/3DUnetCNN#281]
Hi everyone. I am trying to run the "train.py" in the /3DUnetCNN-master\legacy\brats folder. I got this error:

UserWarning: 
This code is using an older version of pydicom, which is no longer 
maintained as of Jan 2017.  You can access the new pydicom features and API 
by installing `pydicom` from PyPI.
See 'Transitioning to pydicom 1.x' section at pydicom.readthedocs.org 
for more information.

  warnings.warn(msg)
2021-01-20 10:57:54.654355: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-01-20 10:57:54.655111: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-01-20 10:57:57.455504: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-01-20 10:57:57.455699: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2021-01-20 10:57:57.458468: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-DMV7TPO
2021-01-20 10:57:57.458777: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-DMV7TPO
2021-01-20 10:57:57.459251: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-01-20 10:57:57.472680: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2015da93370 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-01-20 10:57:57.472933: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Creating validation split...
Number of training steps:  295
Number of validation steps:  37
WARNING:tensorflow:From D:\KHEMIT\3D\3DUnetCNN-master\legacy\brats\unet3d\training.py:88: Model.fit_generator (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
Please use Model.fit, which supports generators.
Epoch 1/500
Traceback (most recent call last):
  File "D:/KHEMIT/3D/3DUnetCNN-master/legacy/brats/train.py", line 125, in <module>
    main(overwrite=config["overwrite"])
  File "D:/KHEMIT/3D/3DUnetCNN-master/legacy/brats/train.py", line 120, in main
    n_epochs=config["n_epochs"])
  File "D:\KHEMIT\3D\3DUnetCNN-master\legacy\brats\unet3d\training.py", line 88, in train_model
    early_stopping_patience=early_stopping_patience))
  File "C:\Python37\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1829, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "C:\Python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\Python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 697, in _initialize
    *args, **kwds))
  File "C:\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Python37\lib\site-packages\tensorflow\python\eager\function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Python37\lib\site-packages\tensorflow\python\framework\func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Python37\lib\site-packages\tensorflow\python\framework\func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    C:\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    D:\KHEMIT\3D\3DUnetCNN-master\legacy\brats\unet3d\metrics.py:33 weighted_dice_coefficient_loss  *
        return -weighted_dice_coefficient(y_true, y_pred)
    D:\KHEMIT\3D\3DUnetCNN-master\legacy\brats\unet3d\metrics.py:26 weighted_dice_coefficient  *
        return K.mean(2. * (K.sum(y_true * y_pred,
    C:\Python37\lib\site-packages\tensorflow\python\ops\math_ops.py:1140 binary_op_wrapper
        raise e
    C:\Python37\lib\site-packages\tensorflow\python\ops\math_ops.py:1124 binary_op_wrapper
        return func(x, y, name=name)
    C:\Python37\lib\site-packages\tensorflow\python\ops\math_ops.py:1456 _mul_dispatch
        return multiply(x, y, name=name)
    C:\Python37\lib\site-packages\tensorflow\python\util\dispatch.py:201 wrapper
        return target(*args, **kwargs)
    C:\Python37\lib\site-packages\tensorflow\python\ops\math_ops.py:508 multiply
        return gen_math_ops.mul(x, y, name)
    C:\Python37\lib\site-packages\tensorflow\python\ops\gen_math_ops.py:6176 mul
        "Mul", x=x, y=y, name=name)
    C:\Python37\lib\site-packages\tensorflow\python\framework\op_def_library.py:506 _apply_op_helper
        inferred_from[input_arg.type_attr]))

    TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type int8 of argument 'x'.

Closing remaining open files:D:\KHEMIT\3D\3DUnetCNN-master\legacy\brats\brats_data.h5...done

Process finished with exit code 1

Please help me with this problem. Thank you.

**Comment by hamza3e** [comment]
Adding y_true = tf.cast(y_true, tf.float32) to loss functions in metrics.py solves the problem.

**Comment by Nhunguts** [comment]
Thank you @hamza3e , I will try.
