### ISSUE TITLE
I didn't make any changes. I couldn't find the file when I ran the sample file.

### ISSUE THREAD

**Issue by liaochuanlin** [ellisdg/3DUnetCNN#318]
Traceback (most recent call last):
  File "/home/aa/anaconda3/envs/unet3d/lib/python3.9/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/home/aa/anaconda3/envs/unet3d/lib/python3.9/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/home/aa/anaconda3/envs/unet3d/lib/python3.9/site-packages/monai/transforms/io/dictionary.py", line 164, in __call__
    data = self._loader(d[key], reader)
  File "/home/aa/anaconda3/envs/unet3d/lib/python3.9/site-packages/monai/transforms/io/array.py", line 263, in __call__
    img = reader.read(filename)
  File "/home/aa/anaconda3/envs/unet3d/lib/python3.9/site-packages/monai/data/image_reader.py", line 907, in read
    img = nib.load(name, **kwargs_)
  File "/home/aa/anaconda3/envs/unet3d/lib/python3.9/site-packages/nibabel/loadsave.py", line 102, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: 'BraTS2020_TrainingData/MICCAI_BraTS2020_TrainingData/BraTS20_Training_085/BraTS20_Training_085_flair.nii'

**Comment by ellisdg** [comment]
That there is no file at 'BraTS2020_TrainingData/MICCAI_BraTS2020_TrainingData/BraTS20_Training_085/BraTS20_Training_085_flair.nii'. You can use the Jupyter Notebook for the Brats example to set the correct file paths to the Brats image files.

**Comment by ellisdg** [comment]
I'm going to close this issue for now, please reopen if you have more questions related to this error. Or feel free to open another issue for a different error/question.
