### ISSUE TITLE
Interface N4BiasFieldCorrection failed to run

### ISSUE THREAD

**Issue by iamyourdaddy** [ellisdg/3DUnetCNN#32]
hi, i have this question when i run your code, but i can't solve it through several days struggle.
the system i use  is win10 x64 platform and i use anaconda python 3.5 run your code. 
and the following is the problem i met:
170813-16:46:22,367 interface INFO:
         [WinError 10038] 在一个非套接字上尝试了一个操作。
Traceback (most recent call last):
  File "C:\my_software\Anaconda\lib\site-packages\nipype\interfaces\base.py", line 1472, in _process
    res = select.select(streams, [], [], timeout)
OSError: [WinError 10038] 在一个非套接字上尝试了一个操作。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\LiRui\Desktop\3d-unet\3DUnetCNN-master\brats\preprocess.py", line 120, in convert_brats_data
    convert_brats_folder(subject_folder, new_subject_folder, background_mask)
  File "C:\Users\LiRui\Desktop\3d-unet\3DUnetCNN-master\brats\preprocess.py", line 105, in convert_brats_folder
    normalize_image(image_file, out_file, background_mask)
  File "C:\Users\LiRui\Desktop\3d-unet\3DUnetCNN-master\brats\preprocess.py", line 89, in normalize_image
    corrected = correct_bias(windowed, append_basename(out_file, "_corrected"))
  File "C:\Users\LiRui\Desktop\3d-unet\3DUnetCNN-master\brats\preprocess.py", line 56, in correct_bias
    done = correct.run()
  File "C:\my_software\Anaconda\lib\site-packages\nipype\interfaces\base.py", line 1081, in run
    runtime = self._run_wrapper(runtime)
  File "C:\my_software\Anaconda\lib\site-packages\nipype\interfaces\base.py", line 1724, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "C:\my_software\Anaconda\lib\site-packages\nipype\interfaces\base.py", line 1755, in _run_interface
    redirect_x=self._redirect_x)
  File "C:\my_software\Anaconda\lib\site-packages\nipype\interfaces\base.py", line 1487, in run_command
    _process()
  File "C:\my_software\Anaconda\lib\site-packages\nipype\interfaces\base.py", line 1475, in _process
    if e[0] == errno.EINTR:
TypeError: 'OSError' object is not subscriptable
Interface N4BiasFieldCorrection failed to run.

it would be very nice if you can help us solve this problem.

**Comment by iamyourdaddy** [comment]
@ellisdg
