### ISSUE TITLE
predict.py issue

### ISSUE THREAD

**Issue by wangxiao-lut** [ellisdg/3DUnetCNN#341]
Hello author, I have run the train.py script and obtained the brats2019_config directory in the brats2019 directory. In this directory, I have obtained the fold1 directory and five files from fold1.json to fold5.json. In the fold1 directory, I have obtained model_best.pth. Currently, I am testing and running predict.py in the brats2019 directory using the command Python/home/wangxiao/3DUNetCNN master/unet3d/scripts/predict.py -- output_directory seg_predict -- model_filename/home/wangxiao/3DUnetCNN master/examples/brats2019/brats2019_config/fold1/model_best. pth -- group bratsvalidation -- config_filename brats2019_config/fold1.json, error reported
(3dunet) wangxiao@OpenStack-Compute:~/3DUnetCNN-master/examples/brats2019$ python /home/wangxiao/3DUnetCNN-master/unet3d/scripts/predict.py --output_directory seg_predict --model_filename /home/wangxiao/3DUnetCNN-master/examples/brats2019/brats2019_config/fold1/model_best.pth --group bratsvalidation --config_filename brats2019_config/fold1.json 
2024-06-12 13:19:04,590 - root - INFO - Config filename: brats2019_config/fold1.json
2024-06-12 13:19:04,593 - root - INFO - Output directory: seg_predict
2024-06-12 13:19:04,593 - root - DEBUG - Found value '[2, 1, 4]' for key 'labels'
2024-06-12 13:19:04,593 - root - DEBUG - Found value 'True' for key 'setup_label_hierarchy'
2024-06-12 13:19:04,593 - root - INFO - Cache dir: /home/wangxiao/3DUnetCNN-master/examples/brats2019/seg_predict/cache
2024-06-12 13:19:04,593 - root - INFO - Filenames key: bratsvalidation_filenames
2024-06-12 13:19:04,593 - root - DEBUG - Could not find value for key 'validation'; default to {}
2024-06-12 13:19:04,593 - root - DEBUG - Found value '1' for key 'validation_batch_size'
2024-06-12 13:19:04,594 - root - DEBUG - Could not find value for key 'prefetch_factor'; default to None
2024-06-12 13:19:04,594 - root - DEBUG - Found value '1' for key 'n_workers'
2024-06-12 13:19:04,594 - root - DEBUG - Found value 'False' for key 'pin_memory'
2024-06-12 13:19:04,594 - LoadImage - DEBUG - required package for reader pydicomreader is not installed, or the version doesn't match requirement.
2024-06-12 13:19:04,594 - LoadImage - DEBUG - required package for reader itkreader is not installed, or the version doesn't match requirement.
2024-06-12 13:19:04,594 - LoadImage - DEBUG - required package for reader nrrdreader is not installed, or the version doesn't match requirement.
Traceback (most recent call last):
  File "/home/wangxiao/3DUnetCNN-master/unet3d/scripts/predict.py", line 105, in <module>
    main()
  File "/home/wangxiao/3DUnetCNN-master/unet3d/scripts/predict.py", line 49, in main
    run_inference(config=config,
  File "/home/wangxiao/3DUnetCNN-master/unet3d/scripts/predict.py", line 76, in run_inference
    dataloader = build_inference_loader(filenames=config[key],
  File "/home/wangxiao/3DUnetCNN-master/unet3d/scripts/script_utils.py", line 189, in build_inference_loader
    _loader = DataLoader(_dataset,
  File "/home/wangxiao/.conda/envs/3dunet/lib/python3.8/site-packages/monai/data/dataloader.py", line 91, in __init__
    super().__init__(dataset=dataset, num_workers=num_workers, **kwargs)
  File "/home/wangxiao/.conda/envs/3dunet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 238, in __init__
    assert prefetch_factor > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by ellisdg** [comment]
Thank you for reporting the issue. I'll change the default prefetch factor to 2.
