### ISSUE TITLE
Attempted relative import in non-package

### ISSUE THREAD

**Issue by sunhuaiqiang** [ellisdg/3DUnetCNN#49]
when I input "from preprocess import convert_brats_data" in bpython or ipython, it returns
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    from preprocess import convert_brats_data
  File "/usr/lib/python2.7/dist-packages/bpython/curtsiesfrontend/repl.py", line 257, in load_module
    module = pkgutil.ImpLoader.load_module(self, name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "preprocess.py", line 15, in <module>
    from .config import config
ValueError: Attempted relative import in non-package

looking forward to your reply, thanks!

**Comment by NongXuXuan** [comment]
Traceback (most recent call last):
  File "/home/user/3DUnetCNN/unet3d/scripts/train.py", line 7, in <module>
    from .train import run_training
ImportError: attempted relative import with no known parent package
