### ISSUE TITLE
command 'N4BiasFieldCorrection' could not be found on host mic233 Interface N4BiasFieldCorrection failed to run. 

### ISSUE THREAD

**Issue by WZFish** [ellisdg/3DUnetCNN#52]
I  run this code on the Linux with python 3.6.3,but there are this problem  

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/DATA/234/zywang/code/3DUnetCNN/brats/preprocess.py", line 120, in convert_brats_data
    convert_brats_folder(subject_folder, new_subject_folder, background_mask)
  File "/DATA/234/zywang/code/3DUnetCNN/brats/preprocess.py", line 105, in convert_brats_folder
    normalize_image(image_file, out_file, background_mask)
  File "/DATA/234/zywang/code/3DUnetCNN/brats/preprocess.py", line 89, in normalize_image
    corrected = correct_bias(windowed, append_basename(out_file, "_corrected"))
  File "/DATA/234/zywang/code/3DUnetCNN/brats/preprocess.py", line 56, in correct_bias
    done = correct.run()
  File "/DATA/234/zywang/anaconda/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1081, in run
    runtime = self._run_wrapper(runtime)
  File "/DATA/234/zywang/anaconda/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1724, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/DATA/234/zywang/anaconda/lib/python3.6/site-packages/nipype/interfaces/base.py", line 1750, in _run_interface
    (self.cmd.split()[0], runtime.hostname))
OSError: command 'N4BiasFieldCorrection' could not be found on host mic233
Interface N4BiasFieldCorrection failed to run.** 

Because I don't familiar with Linux,so I don't know whether I add ANTs to path correctly or not. The .bashrc as shown below:

![tim 20171110201803](https://user-images.githubusercontent.com/18454903/32658319-58c9eb48-c654-11e7-9aea-916e7d125d6b.png)

Do I add the path right? If correct, How can I solve this problem

**Comment by ellisdg** [comment]
From the command line, can you run: 
```$ N4BiasFieldCorrection```
after you have added the ANTs binaries to the directory?

**Comment by MachineLearning-Nerd** [comment]
But can tell me the what is the syntax to run this in the command prompt?
