### ISSUE TITLE
An error from the C extension of tables(HDF5)

### ISSUE THREAD

**Issue by microdyb** [ellisdg/3DUnetCNN#82]
hi,
When the first epoch of training finished, there was an error like this:

Loading previous validation split...
Number of training steps:  583
Number of validation steps:  73
Epoch 1/500
582/583 [============================>.] - ETA: 0s - loss: -0.0576Traceback (most recent call last):
  File "train_isensee2017.py", line 112, in <module>
    main(overwrite=config["overwrite"])
  File "train_isensee2017.py", line 107, in main
    n_epochs=config["n_epochs"])
  File "/home/jc/users/dyb/3d-unet/3DUnetCNN/brats/unet3d/training.py", line 77, in train_model
    early_stopping_patience=early_stopping_patience
  File "/home/jc/miniconda3/envs/deep3d2/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/jc/miniconda3/envs/deep3d2/lib/python3.5/site-packages/keras/engine/training.py", line 2195, in fit_generator
    workers=0)
  File "/home/jc/miniconda3/envs/deep3d2/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/jc/miniconda3/envs/deep3d2/lib/python3.5/site-packages/keras/engine/training.py", line 2310, in evaluate_generator
    generator_output = next(output_generator)
  File "/home/jc/miniconda3/envs/deep3d2/lib/python3.5/site-packages/keras/utils/data_utils.py", line 770, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/home/jc/miniconda3/envs/deep3d2/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/jc/miniconda3/envs/deep3d2/lib/python3.5/site-packages/keras/utils/data_utils.py", line 635, in _data_generator_task
    generator_output = next(self._generator)
  File "/home/jc/users/dyb/3d-unet/3DUnetCNN/brats/unet3d/generator.py", line 155, in data_generator
    skip_blank=skip_blank, permute=permute)
  File "/home/jc/users/dyb/3d-unet/3DUnetCNN/brats/unet3d/generator.py", line 210, in add_data
    data, truth = get_data_from_file(data_file, index, patch_shape=patch_shape)
  File "/home/jc/users/dyb/3d-unet/3DUnetCNN/brats/unet3d/generator.py", line 234, in get_data_from_file
    data, truth = get_data_from_file(data_file, index, patch_shape=None)
  File "/home/jc/users/dyb/3d-unet/3DUnetCNN/brats/unet3d/generator.py", line 239, in get_data_from_file
    y = data_file.root.truth[index, 0]
  File "/home/jc/miniconda3/envs/deep3d2/lib/python3.5/site-packages/tables/array.py", line 652, in __getitem__
    arr = self._read_slice(startl, stopl, stepl, shape)
  File "/home/jc/miniconda3/envs/deep3d2/lib/python3.5/site-packages/tables/array.py", line 756, in _read_slice
    self._g_read_slice(startl, stopl, stepl, nparr)
  File "tables/hdf5extension.pyx", line 1536, in tables.hdf5extension.Array._g_read_slice (tables/hdf5extension.c:18590)
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 173, in H5Dread
    can't read data
  File "H5Dio.c", line 554, in H5D__read
    can't read data
  File "H5Dchunk.c", line 1875, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 2905, in H5D__chunk_lock
    data pipeline read failed
  File "H5Z.c", line 1372, in H5Z_pipeline
    filter returned failure during read
  File "hdf5-blosc/src/blosc_filter.c", line 254, in blosc_filter
    Blosc decompression error

End of HDF5 error back trace

Problems reading the array data.
Closing remaining open files:/home/jc/users/dyb/3d-unet/3DUnetCNN/brats/brats_data.h5...done

I only use one modality, and the patch size=(64,64,64),batch_size=2,validation_size=4,
The python script train_isensee2017.py was running in a conda environment with python 3.5, tensorflow 1.4.1, keras 2.1.3, tables 3.4.2, hdf5 1.8.18 and h5py 2.7.0.

**Comment by mingrui** [comment]
I had a similar problem when trying to run with tensorflow on 2 GPUs.

**Comment by microdyb** [comment]
well,I found when I use pytables instead of tables, the training could go on without error.

**Comment by mingrui** [comment]
hmm... interesting, I will test with pytables later today. Are you using Single or multi gpu?

Thanks!

**Comment by mingrui** [comment]
@microdyb 

Could you clarify "use pytables instead of tables"?

I think in pip they are the same package?

**Comment by microdyb** [comment]
I use conda install pytables.

**Comment by mingrui** [comment]
got it, thanks

**Comment by mingrui** [comment]
@xz2569 No, I wasn't.... I'm still trying tho
