### ISSUE TITLE
early stopping

### ISSUE THREAD

**Issue by DonnieKim411** [ellisdg/3DUnetCNN#85]
Hi,

I just successfully ran the train_isensee2017.py but somehow it stopped too soon?

According to my config, 

`config["early_stop"] = 50  # training will be stopped after this many epochs without the validation loss improving`

So I assumed that it will run 50 epochs at minimum... but somehow it finished right after 1 epoch 

Below is my output from the command line:

```
q1prphtcs18:/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/BRATS/3DUnetCNN/brats:467 % python train_isensee2017.py
/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-02-15 16:01:01.097267: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2018-02-15 16:01:01.329143: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: Tesla K40c major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:24:00.0
totalMemory: 11.17GiB freeMemory: 11.09GiB
2018-02-15 16:01:01.329203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K40c, pci bus id: 0000:24:00.0, compute capability: 3.5)
Loading previous validation split...
('Number of training steps: ', 133)
('Number of validation steps: ', 17)
Epoch 1/500
132/133 [============================>.] - ETA: 7s - loss: -0.0408 Traceback (most recent call last):
  File "train_isensee2017.py", line 117, in <module>
    main(overwrite=config["overwrite"])
  File "train_isensee2017.py", line 112, in main
    n_epochs=config["n_epochs"])
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/BRATS/3DUnetCNN/unet3d/training.py", line 89, in train_model
    early_stopping_patience=early_stopping_patience))
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/keras/engine/training.py", line 2195, in fit_generator
    workers=0)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/keras/engine/training.py", line 2310, in evaluate_generator
    generator_output = next(output_generator)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/keras/utils/data_utils.py", line 762, in get
    raise StopIteration()
StopIteration
Closing remaining open files:/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/BRATS/3DUnetCNN/brats/brats_data.h5...done
```

Shouldn't I expect that the train will run at least up to 50? or am I missing something here?

**Comment by ellisdg** [comment]
It looks like it quit during the validation step, but I'm not sure why. Is
your valudation_batch_size set to 1?

**Comment by kdk411** [comment]
So funny thing happened after your suggestion. I was testing with validation_batch_size = 2 and it stopped after 1 epoch. Then, I changed to 1 and all of the sudden HD4ExtError happened:

```
('Number of training steps: ', 133)
('Number of validation steps: ', 34)
Epoch 1/500
Traceback (most recent call last):
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/keras/utils/data_utils.py", line 654, in _data_generator_task
    generator_output = next(self._generator)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/BRATS/3DUnetCNN/unet3d/generator.py", line 155, in data_generator
    skip_blank=skip_blank, permute=permute)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/BRATS/3DUnetCNN/unet3d/generator.py", line 210, in add_data
    data, truth = get_data_from_file(data_file, index, patch_shape=patch_shape)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/BRATS/3DUnetCNN/unet3d/generator.py", line 238, in get_data_from_file
    x, y = data_file.root.data[index], data_file.root.truth[index, 0]
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/tables/array.py", line 652, in __getitem__
    arr = self._read_slice(startl, stopl, stepl, shape)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/tables/array.py", line 756, in _read_slice
    self._g_read_slice(startl, stopl, stepl, nparr)
  File "tables/hdf5extension.pyx", line 1536, in tables.hdf5extension.Array._g_read_slice (tables/hdf5extension.c:18590)
HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 173, in H5Dread
    can't read data
  File "H5Dio.c", line 554, in H5D__read
    can't read data
  File "H5Dchunk.c", line 1875, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 2905, in H5D__chunk_lock
    data pipeline read failed
  File "H5Z.c", line 1372, in H5Z_pipeline
    filter returned failure during read
  File "hdf5-blosc/src/blosc_filter.c", line 254, in blosc_filter
    Blosc decompression error

End of HDF5 error back trace

Problems reading the array data.
132/133 [============================>.] - ETA: 7s - loss: -0.0417 Traceback (most recent call last):
  File "train_isensee2017.py", line 117, in <module>
    main(overwrite=config["overwrite"])
  File "train_isensee2017.py", line 112, in main
    n_epochs=config["n_epochs"])
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/BRATS/3DUnetCNN/unet3d/training.py", line 89, in train_model
    early_stopping_patience=early_stopping_patience))
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/keras/engine/training.py", line 2195, in fit_generator
    workers=0)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/keras/engine/training.py", line 2310, in evaluate_generator
    generator_output = next(output_generator)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/keras/utils/data_utils.py", line 770, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "<string>", line 3, in reraise
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 173, in H5Dread
    can't read data
  File "H5Dio.c", line 554, in H5D__read
    can't read data
  File "H5Dchunk.c", line 1875, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 2905, in H5D__chunk_lock
    data pipeline read failed
  File "H5Z.c", line 1372, in H5Z_pipeline
    filter returned failure during read
  File "hdf5-blosc/src/blosc_filter.c", line 254, in blosc_filter
    Blosc decompression error

End of HDF5 error back trace

Problems reading the array data.


```
But as you can see, even with the error, it is still training... so I switched back to validation_batch_size = 2 to see if this problem persists, and yes, I can still see the same error:

```
('Number of training steps: ', 133)
('Number of validation steps: ', 17)
Epoch 1/500
Traceback (most recent call last):
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/keras/utils/data_utils.py", line 654, in _data_generator_task
    generator_output = next(self._generator)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/BRATS/3DUnetCNN/unet3d/generator.py", line 155, in data_generator
    skip_blank=skip_blank, permute=permute)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/BRATS/3DUnetCNN/unet3d/generator.py", line 210, in add_data
    data, truth = get_data_from_file(data_file, index, patch_shape=patch_shape)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/BRATS/3DUnetCNN/unet3d/generator.py", line 238, in get_data_from_file
    x, y = data_file.root.data[index], data_file.root.truth[index, 0]
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/tables/array.py", line 652, in __getitem__
    arr = self._read_slice(startl, stopl, stepl, shape)
  File "/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/deep_python/lib/python2.7/site-packages/tables/array.py", line 756, in _read_slice
    self._g_read_slice(startl, stopl, stepl, nparr)
  File "tables/hdf5extension.pyx", line 1536, in tables.hdf5extension.Array._g_read_slice (tables/hdf5extension.c:18590)
HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 173, in H5Dread
    can't read data
  File "H5Dio.c", line 554, in H5D__read
    can't read data
  File "H5Dchunk.c", line 1875, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 2905, in H5D__chunk_lock
    data pipeline read failed
  File "H5Z.c", line 1372, in H5Z_pipeline
    filter returned failure during read
  File "hdf5-blosc/src/blosc_filter.c", line 254, in blosc_filter
    Blosc decompression error

End of HDF5 error back trace

Problems reading the array data.
 12/133 [=>............................] - ETA: 18:49 - loss: -0.0478
```

So something is surely up with HDF5 C extension... yet, it can train regardless of the validation batch size, which makes sense since training itself shouldn't depend on the validation batch size, unless the data is corrupted.

I can find some thread related to this error [here](https://github.com/ellisdg/3DUnetCNN/issues/82). 

So let me try this first and see if I can resolve the problem...

Do you mind if you can verify the version of pytables for me?

**Comment by ljljlj02** [comment]
I also stopped after only running one epoch,have you solved it?
