### ISSUE TITLE
validation steps

### ISSUE THREAD

**Issue by primentropy** [ellisdg/3DUnetCNN#86]
Hi, thank you for your work! It helps me a lot.

I run into a issue after I convert the brats data and start the training by : python train_isensee2017.py or  python train.py, but it show me some problem with validation steps. Any suggestions about my issue?

(tensorflow)root@ubuntu:~/3DUnetCNN/brats# python train_isensee2017.py
Using TensorFlow backend.
2018-02-23 09:35:45.097413: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
Loading previous validation split...
Number of training steps:  0
Number of validation steps:  0
Traceback (most recent call last):
  File "train_isensee2017.py", line 117, in <module>
    main(overwrite=config["overwrite"])
  File "train_isensee2017.py", line 112, in main
    n_epochs=config["n_epochs"])
  File "/root/3DUnetCNN/unet3d/training.py", line 88, in train_model
    early_stopping_patience=early_stopping_patience))
  File "/root/tensorflow/lib/python3.4/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/root/tensorflow/lib/python3.4/site-packages/keras/engine/training.py", line 2115, in fit_generator
    raise ValueError('`validation_steps=None` is only valid for a'
ValueError: `validation_steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class.
Closing remaining open files:/root/3DUnetCNN/brats/brats_data.h5...done

Thank you!

**Comment by nitinsatpute** [comment]
Hi,
I am facing the same issue. Could you have a look?

**Comment by Joeng22** [comment]
File train.py/ train_isensee2017.py 
line No.46

set,
config["overwrite"] = True (False by default)
"
(original)
config["overwrite"] = False  # If True, will previous files. If False, will use previously written files.
"

Now working fine

**Comment by nitinsatpute** [comment]
Hi,
Thanks for the reply.
Above problem is solved but python is crashing with segmentation fault.

:193] kernel reported version is: 384.111.0
2018-03-09 11:16:28.214920: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:303] kernel version 384.111.0 does not match DSO version 387.26.0 -- cannot find working devices in this configuration
Creating validation split...
Number of training steps:  581
Number of validation steps:  76
Epoch 1/500
Segmentation fault (core dumped)

**Comment by nitinsatpute** [comment]
After updating driver, error remains the same. This is using python3 train.py

totalMemory: 3.95GiB freeMemory: 2.68GiB
2018-03-09 13:14:06.805089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
Creating validation split...
Number of training steps:  152
Number of validation steps:  24
Epoch 1/500
Segmentation fault (core dumped)

**Comment by nitinsatpute** [comment]
Hi,
for train.py, batch size was same as suggested. For train_isensee2017.py, it was 1 and 2 before. I have tried experimenting with it including config["batch_size"] = 6 and config["validation_batch_size"] = 12, the problem remains the same.

TotalMemory: 3.95GiB freeMemory: 3.42GiB
2018-03-14 09:21:01.608187: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
Creating validation split...
Number of training steps:  97
Number of validation steps:  14
Epoch 1/500
Segmentation fault (core dumped)

**Comment by nitinsatpute** [comment]
for train.py when 
config["batch_size"] = 1
config["validation_batch_size"] = 2

totalMemory: 3.95GiB freeMemory: 3.32GiB
2018-03-14 09:49:05.512269: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
Creating validation split...
Number of training steps:  934
Number of validation steps:  127
Epoch 1/500
Segmentation fault (core dumped)

**Comment by ellisdg** [comment]
I don't think 4GB is enough memory to train the model. I'm guessing that is probably your issue. You can try patch-wise training using small patches. I would recommend, though, using a GPU with more memory (if you have access to one).

**Comment by aohang111** [comment]
@ellisdg  seems my Gpu memory is enough, but I got the same error:

[ahsh@minsky-sh-01 brats]$ python train_isensee2017.py
Using TensorFlow backend.                                                                                             
/usr/lib/python3.4/site-packages/tensorflow/python/keras/backend.py:4785: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/ahsh/.keras/keras.json' mode='r' encoding='UTF-8'>                                                  
  _config = json.load(open(_config_path))
2019-01-17 05:31:18.527290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:  name: Tesla P100-SXM2-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.4805
pciBusID: 0006:01:00.0                                                                                                
totalMemory: 15.90GiB freeMemory: 15.61GiB
2019-01-17 05:31:18.591319: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 1 with properties: name: Tesla P100-SXM2-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.4805 
pciBusID: 0007:01:00.0
totalMemory: 15.90GiB freeMemory: 15.61GiB
2019-01-17 05:31:18.591377: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0, 1
2019-01-17 05:31:19.820104: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor
 with strength 1 edge matrix:
2019-01-17 05:31:19.820151: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 1 
2019-01-17 05:31:19.820164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N Y  
2019-01-17 05:31:19.820173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 1:   Y N  
2019-01-17 05:31:19.821076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15127 MB memory) -> physical GPU (device: 0, name: Tesla P100-SXM2-16GB, pci bus id: 0006:01:00.0, compute capability: 6.0)                                                                     
2019-01-17 05:31:19.917732: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 15127 MB memory) -> physical GPU (device: 1, name: Tesla P100-SXM2-16GB, pci bus id: 0007:01:00.0, compute capability: 6.0)                                                                     Loading previous validation split...  
Number of training steps:  228 
Number of validation steps:  29
/usr/lib64/python3.4/site-packages/keras/utils/data_utils.py:651: DeprecationWarning: `wait_time` is not used anymore.DeprecationWarning)
Epoch 1/10                                                                                                           
Segmentation fault   

I am try to modify 
config["image_shape"] = (112, 112, 112)
config["patch_shape"] = (64, 64, 64) 
. 
and try to do  as issue  https://github.com/ellisdg/3DUnetCNN/issues/58
suggested. 
but still have this problem. any suggestion?      
thanks in advance

**Comment by jlzung** [comment]
I'm getting the same error as @aohang111 above. The program returns a segmentation fault right after printing "Epoch 1/xx". (Does not say "core dumped" as others have reported)

Faulthandler gives me the following traceback:
Current thread 0x00002ae04f541700 (most recent call first):
  File "/home/xxx/.local/lib/python3.6/site-packages/tables/array.py", line 766 in _read_slice
  File "/home/xxx/.local/lib/python3.6/site-packages/tables/array.py", line 662 in __getitem__
  File "/home/xxx/3DUnetCNN/unet3d/generator.py", line 238 in get_data_from_file
  File "/home/xxx/3DUnetCNN/unet3d/generator.py", line 210 in add_data
  File "/home/xxx/3DUnetCNN/unet3d/generator.py", line 155 in data_generator
  File "/home/xxx/.local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 626 in next_sample
  File "/home/xxx/.conda/envs/cnn2/lib/python3.6/multiprocessing/pool.py", line 119 in worker
  File "/home/xxx/.conda/envs/cnn2/lib/python3.6/threading.py", line 864 in run
  File "/home/xxx/.conda/envs/cnn2/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/xxx/.conda/envs/cnn2/lib/python3.6/threading.py", line 884 in _bootstrap

Does anyone have any ideas? The validation and training generators appear to be working correctly.

**Comment by Jasmine312** [comment]
> Hi,
> Thanks for the reply.
> Above problem is solved but python is crashing with segmentation fault.
> 
> :193] kernel reported version is: 384.111.0
> 2018-03-09 11:16:28.214920: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:303] kernel version 384.111.0 does not match DSO version 387.26.0 -- cannot find working devices in this configuration
> Creating validation split...
> Number of training steps: 581
> Number of validation steps: 76
> Epoch 1/500
> Segmentation fault (core dumped)

HI, I am facing the same issue .can you tell me the way you solved  the problem which  ValueError: validation_steps=None is only valid for a generator based on the keras.utils.Sequence class. Please specify validation_steps or use the keras.utils.Sequence class?

**Comment by GiovannaMariaDimitri** [comment]
> @aohang111 I agree that you should have plenty of memory for this model. I would try updating all the dependencies, and see if you get the same errors.

Hi, I am currently encurring the same issue with the . @ellisdg did you manage to check dependencies and see which could be the problem?

Thanks

Giovanna
